### ISSUE TITLE
Conformance classes

### ISSUE THREAD

**Issue by evanp** [w3c-social/post-type-discovery#10]
Can we define conformance classes for implementers of PTD?

**Comment by tantek** [comment]
We should. I can think of a couple useful ones from existing implementation experience: 
- Type Discovery Function - consumes untyped posts from an untyped format or protocol, and outputs a simple string of the type output of the algorithm
- AS2 Proxy - consumes untyped posts from an untyped format or protocol, and outputs valid AS2 JSON or other object structures

**Comment by tantek** [comment]
The specification must use at least one MUST requirement (feedback from @bigbluehat), e.g. in the algorithm.

**Comment by tantek** [comment]
No longer a CR-blocker (because PTD is Note-track), however, still useful. Keeping issue open accordingly.

**Comment by tantek** [comment]
Defined the above two mentioned conformance classes with this commit: https://github.com/tantek/post-type-discovery/commit/f9c01dfc8440f092cc03c3de3d2321095539da3e
