### ISSUE TITLE
Normative references to unstable parts of h-entry

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/post-type-discovery#11]
Eg. 'like-of' is a draft property in h-entry but is normatively referenced in the PTD algorithm.

(I understood that h-entry could be normatively referenced only concerning parts that are stable, and 'draft properties' indicates instability).

**Comment by tantek** [comment]
This is a CR-blocker.

**Comment by tantek** [comment]
In general the "referenced only concerning parts that are stable" applies to CRs which themselves are supposed to be stable.

Until then I plan to expand post type discovery to expand any new implied post types that have shown success in the wild (publishing and consuming code).

**Comment by tantek** [comment]
like-of and repost-of have matured and been upgraded to core in h-entry per https://github.com/microformats/h-entry/issues/2 and https://github.com/microformats/h-entry/issues/3

Updated h-entry version: http://microformats.org/wiki/index.php?title=h-entry&oldid=65900

That leaves:
* photo
* video

which are still draft for now, but I believe there is likely sufficient evidence for each. Will document and iterate on those next.

**Comment by tantek** [comment]
For reference:
* u-photo: https://github.com/microformats/h-entry/issues/4
* u-video: https://github.com/microformats/h-entry/issues/5

**Comment by tantek** [comment]
Now that PTD is Note-track, I don't think this is an issue any more, and we can close it. Any objection @rhiaro? If not, please close. Thanks!
