### ISSUE TITLE
What is a "valid value" for an "rsvp" property?

### ISSUE THREAD

**Issue by dret** [w3c-social/post-type-discovery#14]
https://www.w3.org/TR/2016/WD-post-type-discovery-20160728/#algorithm states 'If the post has an "rsvp" property with a valid value', but it does not seem to be defined in the spec what a valid value for that property is. maybe some clarification is needed?

**Comment by tantek** [comment]
Unintended issue auto-closure, re-opening

**Comment by dret** [comment]
looks good to me, if that's a closed set. thanks!

**Comment by tantek** [comment]
That's a closed set, changeable by usual deliberate change control for the referenced specifications. If that's ok, please close the issue. Thanks!

Update: to be clear, this set of values is stable, and I don't expect them to change, but if they do, they would change via explicit change control of the underlying spec and a new issue on this spec.

**Comment by dret** [comment]
sounds good enough, thanks a lot!
