### ISSUE TITLE
add 'Else' to the last line of the algorithm 

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/post-type-discovery#18]
I think 'Else' should be added to the last line of the section 3 algorithm

If the post has no "name" property 
  or has a "name" property with an empty string value (or no value) 
Then it is a note post.
Take the first non-empty value of the "name" property
Trim all leading/trailing whitespace
Collapse all sequences of internal whitespace to a single space (0x20) character each
Do the same with the content
If this processed "name" property value is NOT a prefix of the processed content, 
Then it is an article post.
[Else] It is a note post.

**Comment by tantek** [comment]
Good editorial improvement.
