### ISSUE TITLE
Response Type: move "reply" to 2nd to last to enable p-summary fallback use-cases

### ISSUE THREAD

**Issue by tantek** [w3c-social/post-type-discovery#25]
Based on implementer feedback from @aaronpk and @sebsel, it may make more sense to move the "reply" recognition step to 2nd to last in the Response Type Algorithm, that is, right before the "else it is a mention".

Specifically, anyone posting a "like", "repost", "RSVP", (or any other new response type!) has incentive to provide u-in-reply-to fallback plain text equivalent perhaps in p-summary that expresses the reaction/response as prose, e.g.:
* like: "Tantek liked this post"
* repost: "Tantek reposted this at URL"
* tag-of: "Tantek tagged Sebastian in this photo"

This way even if the receiving site only supports receiving Webmention replies/comments, something sensible will still show up, and provide a good experience to the author of the response, the author of the post, and any readers of the post.

If we formalize this kind of fallback markup as a publishing guideline (perhaps a feature request for https://github.com/microformats/h-entry) it also provides a nice path forward for expanding response types over time that provide meaningful behavior even to existing systems without explicit support for the new response types.

**Comment by prtksxna** [comment]
You'll have to help me understand this a bit better. Are you saying that *newer* kinds of replies, for example [edits](http://indieweb.org/edit), should also include the `u-in-reply-to` class along with their own class (`u-edit-of` in this case) so that the author of the post can at least show it as a reply (if *reply* becomes the 2<sup>nd</sup> to last step)?

**Comment by tantek** [comment]
@prtksxna precisely! All (especially newer) responses should include the u-in-reply-to to enable fallback behavior with p-summary with any consuming code that may or may not understand that particular type of response.

**Comment by tantek** [comment]
Discussed in https://www.w3.org/wiki/Socialwg/2017-07-25-minutes#Post_Type_Discovery today's Social Web WG telecon, with resolution of accepting editor proposal, and approving new WD with that change.

**Comment by prtksxna** [comment]
Great! Thanks for the logs.

**Comment by tantek** [comment]
Changes made in repo and published updated WD: https://www.w3.org/TR/2017/WD-post-type-discovery-20170801/
