### ISSUE TITLE
Present algoritm with elif or as return value?

### ISSUE THREAD

**Issue by kevinmarks** [w3c-social/post-type-discovery#3]
the if nesting is a little unclear as you have to remember the 
"following these steps until reaching the first "it is a(n) ... post" statement at which point the "..." is the discovered post type."

It may be clearer with an elif structure or a return

**Comment by tantek** [comment]
I'm going to consider this as editorial rather than substantial, yet keep it open as a reminder to re-assess / iterate on the readability/understandability of the algorithm.

**Comment by tantek** [comment]
Update: have decided to output (return) a list of post types, including a primary post type, so this issue is likely to no longer apply after rewriting the algorithm accordingly.

I'd like to close this issue without changes accordingly.

**Comment by kevinmarks** [comment]
Makes sense - that is a better answer for composite posts too.

**Comment by tantek** [comment]
Closing per "Makes sense" agreement from commenter.
