### ISSUE TITLE
Additional use case(s)

### ISSUE THREAD

**Issue by dissolve** [w3c-social/post-type-discovery#33]
I use PTD to discover all post types of comments and was trying to consider where I actually use that information.   Essentially I need to discover post type for UI reasons only.   For rolling up likes in to one section.  For a list of notifications to myself (Alice commented on your photo, 7 people liked your video).   

Additionally this would be useful for feedback when posting.  "Your reply to Cathy's video has been posted"

Perhaps we could add some additional use case to document these.

**Comment by tantek** [comment]
added a couple of use-cases to cover what you mentioned in commit https://github.com/tantek/post-type-discovery/commit/c226297dd2a1b85435798f34880a09480785e154

If that looks good to you, please close. Thanks!

**Comment by dissolve** [comment]
looks good to me :+1:
