### ISSUE TITLE
Add to "why" section, how it fits in with other Social Web WG drafts

### ISSUE THREAD

**Issue by tantek** [w3c-social/post-type-discovery#4]
per request from Sandro

**Comment by sandhawke** [comment]
Including how it's helping to AS2 without belonging in the AS2 spec.

**Comment by tantek** [comment]
In particular, the AS2 makes 'type' optional, which is a desired characteristic, that leads to the (potential) need for this spec.

AS2 itself is much more mature and reviewed than this spec, thus it makes sense to allow AS2 to move forward _without_ Post Type Discovery included inline.

**Comment by tantek** [comment]
Some more notes.

Add to introduction.

Post type discovery helps provide a bridge between systems without explicit post types (e.g. Micropub, jf2) to systems with explicit post types (e.g. ActivityPub, AS2).
